/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Versioning {
  static getGitHash(): string
  static getGitBranch(): string
  static getRustInfo(): string
}
export class DateFns {
  static prettyFromMs(ms: number): string
}
export class MapData {
  static isRealMap(data: Buffer): boolean | null
}
